version: '3.8'

services:
  app:
    image: my-flask-app
    build : .
    ports:
      - "5000:5000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
      - ./app.py:/app/app.py